### ISSUE TITLE
Amazon IOT with certificates fails with NullPointerException

### ISSUE THREAD

**Issue by smougenot** [eclipse/paho.mqtt-spy#11]
Version : 0.5.4 (build 52)
java 8 : OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)

Trying to use certificate authentication on Amazon IOT fails with error :
```
pl.baczkowicz.spy.exceptions.ConfigurationException: Invalid configuration parameters
	at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.<init>(MqttConnectionDetailsWithOptions.java:91)
	at pl.baczkowicz.mqttspy.connectivity.MqttRuntimeConnectionProperties.<init>(MqttRuntimeConnectionProperties.java:34)
	at pl.baczkowicz.mqttspy.ui.MqttConnectionViewManager.openConnection(MqttConnectionViewManager.java:152)
	at pl.baczkowicz.mqttspy.ui.controllers.EditMqttConnectionController$6.run(EditMqttConnectionController.java:461)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
Caused by: pl.baczkowicz.spy.exceptions.SpyException: Cannot create TLS/SSL connection
	at pl.baczkowicz.spy.security.SecureSocketFactoryBuilder.getSocketFactory(SecureSocketFactoryBuilder.java:106)
	at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.populateMqttConnectOptions(MqttConnectionDetailsWithOptions.java:175)
	at pl.baczkowicz.mqttspy.connectivity.MqttConnectionDetailsWithOptions.<init>(MqttConnectionDetailsWithOptions.java:87)
	... 10 more
Caused by: java.lang.NullPointerException
	at pl.baczkowicz.spy.security.SecureSocketUtils.getKeyManagerFactory(SecureSocketUtils.java:198)
	at pl.baczkowicz.spy.security.SecureSocketFactoryBuilder.getSocketFactory(SecureSocketFactoryBuilder.java:99)
	... 12 more
```

But it works fine with the same certificates (and key) using mosquitto_pub or MQTT.fx.
Settings look like this on MQTT-spy
![capture d ecran de 2017-01-16 10-28-05](https://cloud.githubusercontent.com/assets/1217669/21977500/b3017176-dbd6-11e6-8c4f-f16eeb38ab72.png)

The same files (certificates and key) used on MQTT.fx are working fine
![capture d ecran de 2017-01-16 10-16-12](https://cloud.githubusercontent.com/assets/1217669/21977363/288d6c8e-dbd6-11e6-9cc2-99ee1d91e085.png)

**Comment by kamilfb** [comment]
hi @smougenot,

Sorry for taking so long to reply. Looks like this is because the password is ending up as null as opposed to empty.

In the meantime you could try setting the client key password. I will get a fix for that this week.
