### ISSUE TITLE
Unable to run any example code without changes

### ISSUE THREAD

**Issue by stevebates** [eclipse/paho.mqtt-spy#12]
Hi guys,

Thanks for the response on Twitter, I've setup mqtt-spy on Ubuntu server 16.04, using my existing Java which I have installed and working for other apps. Everything is pretty much defaulted or has been but no matter what I try, it doesn't like any script. Java version is reported as below:

```
root@jupiter:~/mqtt-spy# java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

The actual errors I'm seeing are:

```
root@jupiter:~/mqtt-spy# java -jar mqtt-spy-daemon-0.1.0.jar "/root/mqtt-spy/daemon-configuration.xml"
2017-02-22 11:14:39,999 INFO  [MqttSpyDaemon                 ]  - #######################################################
2017-02-22 11:14:40,004 INFO  [MqttSpyDaemon                 ]  - ### Starting mqtt-spy-daemon v0.1.0 (build 80)
2017-02-22 11:14:40,004 INFO  [MqttSpyDaemon                 ]  - ### If you find it useful, see how you can help at http://kamilfb.github.io/mqtt-spy/
2017-02-22 11:14:40,004 INFO  [MqttSpyDaemon                 ]  - ### To get release updates follow @mqtt_spy on Twitter 
2017-02-22 11:14:40,004 INFO  [MqttSpyDaemon                 ]  - #######################################################
2017-02-22 11:14:40,045 INFO  [ConfigurationUtils            ]  - Auto-complete for server URI (localhost -> tcp://localhost)
2017-02-22 11:14:40,099 INFO  [ReconnectionManager           ]  - Starting connection mqtt-spy-daemon-2@tcp://localhost
2017-02-22 11:14:40,152 INFO  [SimpleMqttConnection          ]  - Successfully connected to mqtt-spy-daemon-2@tcp://localhost
2017-02-22 11:14:40,692 INFO  [BaseScriptManager             ]  - Adding script /root/mqtt-spy/script1.js
2017-02-22 11:14:40,701 INFO  [BaseMqttConnection            ]  - Subscribed to pa340037001547353236343033/#
2017-02-22 11:14:40,725 INFO  [BaseScriptManager             ]  - Adding script /root/mqtt-spy/script1.js
2017-02-22 11:14:40,943 ERROR [ScriptRunner                  ]  - Script execution exception
javax.script.ScriptException: ReferenceError: "receivedMessage" is not defined in <eval> at line number 4
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
        at pl.baczkowicz.spy.scripts.ScriptRunner.runScript(ScriptRunner.java:138)
        at pl.baczkowicz.spy.scripts.ScriptRunner.run(ScriptRunner.java:99)
        at pl.baczkowicz.spy.scripts.BaseScriptManager.runScript(BaseScriptManager.java:387)
        at pl.baczkowicz.spy.scripts.BaseScriptManager.runScript(BaseScriptManager.java:358)
        at pl.baczkowicz.mqttspy.connectivity.BaseMqttConnection.subscribe(BaseMqttConnection.java:304)
        at pl.baczkowicz.mqttspy.daemon.connectivity.SimpleMqttConnectionRunnable.run(SimpleMqttConnectionRunnable.java:92)
        at java.lang.Thread.run(Thread.java:745)
Caused by: <eval>:4 ReferenceError: "receivedMessage" is not defined
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
        at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
        at jdk.nashorn.internal.scripts.Script$Recompilation$1$24$\^eval\_.publishReply(<eval>:4)
        at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:11)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        ... 11 more
2017-02-22 11:14:40,947 INFO  [BaseScriptManager             ]  - No setup function present
```

With the following configuration:

```
<?xml version="1.0" encoding="UTF-8"?>
<mqttspydc:MqttSpyDaemonConfiguration xmlns:mqttspydc="http://baczkowicz.pl/mqtt-spy/daemon/configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<Connection>

		<ServerURI>localhost</ServerURI>

		<ClientID>mqtt-spy-daemon-2</ClientID>

		<UserCredentials>
			<Username>[removed]</Username>
			<Password>[removed]</Password>
		</UserCredentials>

		<CleanSession>true</CleanSession>
		<ConnectionTimeout>10</ConnectionTimeout>
		<KeepAliveInterval>10</KeepAliveInterval>

		<ReconnectionSettings>
			<RetryInterval>5000</RetryInterval>             
			<Resubscribe>true</Resubscribe>
		</ReconnectionSettings>

		<MessageLog>XML_WITH_PLAIN_PAYLOAD</MessageLog>

		<Subscription topic="pa340037001547353236343033/#" qos="0" scriptFile="/root/mqtt-spy/script1.js"/>
    
		<RunningMode>CONTINUOUS</RunningMode>
		
	</Connection>

</mqttspydc:MqttSpyDaemonConfiguration>
```

As mentioned, script1 contains the default demo code so:

```
function publishReply()
{
    mqttspy.publish(
            "/reply", "<simpleReply><topic>" + receivedMessage.getTopic() + "</topic>" 
            + "<payload><![CDATA[" + receivedMessage.getMessage() + "]]></payload>"
            + "</simpleReply>", 0, false);

    return true;
}

publishReply();
```

If i simplify the script then it runs but only once, MQTT messages are logged in the backend but it doesn't appear to react to them.

This is while running mqtt-spy-daemon 0.1.0.

Thanks, Steve.

**Comment by kamilfb** [comment]
Hi @stevebates,

Have you tried mqtt-spy-daemon version 0.2.0 beta?

**Comment by kamilfb** [comment]
@stevebates Sorry for taking so long to reply. I recon this is because the script is in an old format. 

Could you try this instead:

function onMessage()
{	
	mqtt.publish(
			"/reply", "<simpleReply><topic>" + receivedMessage.getTopic() + "</topic>" 
			+ "<payload><![CDATA[" + receivedMessage.getPayload() + "]]></payload>"
			+ "</simpleReply>", 0, false);

	return true;
}
