### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Divirion** [eclipse/paho.mqtt-spy#21]
I am facing a memory issue when live plotting data. RAM usage goes up and up as data arrives until it eventually freezes my whole computer.
I'm running on Ubuntu 16.04 using mosquitto as my mqqt message broker. I tried using both 0.5.4 and 0.6.0 versions with no luck.

**Comment by kamilfb** [comment]
hi @Divirion , could you provide some more information on what live data you are plotting and how quickly it grows?

**Comment by Marwe** [comment]
In the attachment you can see the memory consumption logged in mqtt-spy via MQTT.
Only few minutes and all memory is used up.

Same thing observed with these versions:
mqtt-spy-0.5.3-jar-with-dependencies.jar
mqtt-spy-0.6.0-beta-b56-jar-with-dependencies.jar

I published the memory usage with this bash snippet:
`while true ; do mosquitto_pub -t 'mqtt-spy/memoryusage' -m "$(ps -C "java -jar /path/to/mqtt-spy-0.6.0-beta-b56-jar-with-dependencies.jar" -o vsz=)"; sleep 1; done`

Maybe someone observes the same and has the possibility to track it down?

The amount of different messages was roughly 20 in total with 1 Hz (10 messages/second), one value being plotted.

![mqtt-spy_memoryplot](https://cloud.githubusercontent.com/assets/2165004/26184547/fb4cfe32-3b85-11e7-858a-552c8d3ab5f8.png)

This issue was reported to the wrong repo first:
https://github.com/kamilfb/mqtt-spy/issues/113

**Comment by Divirion** [comment]
Hello @kamilfb,
I am plotting a simple data like this. A new data is received every 10ms. 
![dataplotted](https://cloud.githubusercontent.com/assets/19845512/26192599/b66c8e86-3bb2-11e7-8987-d2a396a533b4.png)

Here is the RAM usage growing (starts at 40) :
![capture du 2017-05-18 10-11-43](https://cloud.githubusercontent.com/assets/19845512/26192634/d3b494f2-3bb2-11e7-93de-81c402ebbb84.png)

and here is when i exit mqtt-spy right after.

![stop_mqtt_spy](https://cloud.githubusercontent.com/assets/19845512/26192662/ea9c6852-3bb2-11e7-86c6-395a479a29e9.png)

**Comment by edwin-oetelaar** [comment]
I am having memory leak issues too.
After a few days the whole application freezes up, consuming lots of memory.
I am not plotting anything, just using the list view to see the topics and messages.
Some messages that are received are 2.5 MB in size, maybe this is an issue. 
I receive about  1 GB of messages each day total volume.

The logging shows :+1: 2017-07-24 14:24:46,849 DEBUG [BaseViewManager               ]  - Setting title pane width to 1542.0
2017-07-24 14:24:46,849 DEBUG [BaseViewManager               ]  - Setting title pane width to 1542.0
2017-07-24 14:24:46,849 DEBUG [BaseViewManager               ]  - Setting title pane width to 1556.0
2017-07-24 14:24:46,850 DEBUG [BaseViewManager               ]  - Setting title pane width to 1556.0
2017-07-24 14:24:46,850 DEBUG [BaseViewManager               ]  - Setting title pane width to 1556.0
2017-07-24 14:24:47,450 DEBUG [BaseViewManager               ]  - Setting title pane width to 1542.0
2017-07-24 14:26:47,587 ERROR [SpyUncaughtExceptionHandler   ]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-07-24 14:26:48,212 ERROR [SpyUncaughtExceptionHandler   ]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-07-24 14:26:48,830 ERROR [SpyUncaughtExceptionHandler   ]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-07-24 14:26:49,449 ERROR [SpyUncaughtExceptionHandler   ]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-07-24 14:26:51,936 ERROR [SpyUncaughtExceptionHandler   ]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
 

And also 


2017-07-24 13:01:32,715 DEBUG [MqttSubscriptionViewManager   ]  - Updating subscription tab context menu [test, CONNECTED, true]
2017-07-24 13:01:32,715 DEBUG [MqttSubscriptionViewManager   ]  - Updating subscription tab context menu [test/+, CONNECTED, true]
2017-07-24 13:01:32,715 DEBUG [MqttSubscriptionViewManager   ]  - Updating subscription tab context menu [test/+/+, CONNECTED, true]
2017-07-24 14:00:27,352 ERROR [SpyUncaughtExceptionHandler   ]  - Thread Thread[MQTT Rec: oetelaar_mqttspy123,5,main] failed with java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Jul 24, 2017 2:02:24 PM org.eclipse.paho.client.mqttv3.internal.ClientState checkForActivity
SEVERE: oetelaar_mqttspy123: Timed out as no activity, keepAlive=60,000 lastOutboundActivity=1,500,897,684,660 lastInboundActivity=1,500,897,627,088 time=1,500,897,744,660 lastPing=1,500,897,684,660
2017-07-24 14:02:24,662 ERROR [MqttCallbackHandler           ]  - Connection oetelaar_mqttspy123@*******so4.nl lost
Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.checkForActivity(ClientState.java:661)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:732)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.checkForActivity(ClientComms.java:718)
	at org.eclipse.paho.client.mqttv3.TimerPingSender$PingTask.run(TimerPingSender.java:77)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
2017-07-24 14:02:24,663 DEBUG [MqttAsyncConnection           ]  - Unsubscribing from test
2017-07-24 14:02:24,663 WARN  [BaseMqttConnection            ]  - Client not connected
2017-07-24 14:02:24,663 INFO  [BaseMqttConnection            ]  - Successfully unsubscribed from test
2017-07-24 14:02:24,663 DEBUG [MqttSubscriptionViewManager   ]  - Updating subscription tab context menu [test, DISCONNECTED, false]
2017-07-24 14:02:24,664 DEBUG [MqttAsyncConnection           ]  - Unsubscribing from test/+
2017-07-24 14:02:24,664 WARN  [BaseMqttConnection            ]  - Client not connected
2017-07-24 14:02:24,664 INFO  [BaseMqttConnection            ]  - Successfully unsubscribed from test/+
2017-07-24 14:02:24,664 DEBUG [MqttSubscriptionViewManager   ]  - Updating subscription tab context menu [test/+, DISCONNECTED, false]
2017-07-24 14:02:24,664 DEBUG [MqttAsyncConnection           ]  - Unsubscribing from test/+/+
2017-07-24 14:02:24,664 WARN  [BaseMqttConnection            ]  - Client not connected

Maybe you have some insights to why this happening?
Thanks for the very nice program, I really like it.
