### ISSUE TITLE
mqtt-spy can not be start

### ISSUE THREAD

**Issue by WernerSch** [eclipse/paho.mqtt-spy#25]
Hello

i hop i am on the right place here, because i find no forum. I get alwys this in my terminal. Can you hel me?

root@MQTT:~# cd /home/pi
root@MQTT:/home/pi# java -jar mqtt-spy1.jar
2017-06-24 22:28:41,074 ERROR [BaseConfigurationUtils        ]  - Invalid number format 
2017-06-24 22:28:45,157 DEBUG [MqttViewManager               ]  - Selected perspective = DEFAULT
2017-06-24 22:28:45,171 ERROR [MqttStatsFileIO               ]  - Cannot read the statistics file from /root/mqtt-spy/mqtt-spy-stats.xml
java.io.FileNotFoundException: Cannot load the file from /root/mqtt-spy/mqtt-spy-stats.xml
	at pl.baczkowicz.spy.xml.XMLParser.loadFromFile(XMLParser.java:359)
	at pl.baczkowicz.mqttspy.ui.stats.MqttStatsFileIO.loadStats(MqttStatsFileIO.java:57)
	at pl.baczkowicz.spy.ui.stats.StatisticsManager.loadStats(StatisticsManager.java:298)
	at pl.baczkowicz.mqttspy.ui.controllers.MqttSpyMainController.init(MqttSpyMainController.java:154)
	at pl.baczkowicz.mqttspy.ui.MqttViewManager.createMainWindow(MqttViewManager.java:151)
	at pl.baczkowicz.mqttspy.Main.start(Main.java:90)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.lang.Thread.run(Thread.java:748)
2017-06-24 22:28:48,527 INFO  [MqttViewManager               ]  - Default configuration file present (/root/mqtt-spy/mqtt-spy-configuration.xml) = false
2017-06-24 22:28:48,529 DEBUG [BaseConfigurationManager      ]  - Creating root group called 'All connections'
2017-06-24 22:28:50,886 DEBUG [ControlPanelController        ]  - Retrieved version info = pl.baczkowicz.spy.ui.generated.versions.SpyVersions@964cca[releaseStatuses=pl.baczkowicz.spy.ui.generated.versions.ReleaseStatuses@f3f644[releaseStatus={pl.baczkowicz.spy.ui.generated.versions.ReleaseStatus@d05085[fromVersion=0.5.1-42, toVersion=0.5.1-42, updateTitle=Bugs have been found in this release!, updateDetails=Best to update to version 0.5.4 (build 52)., updateStatus=CRITICAL],pl.baczkowicz.spy.ui.generated.versions.ReleaseStatus@1205f43[fromVersion=0.5.1-44, toVersion=0.5.1-44, updateTitle=Bugs have been found in this release!, updateDetails=Best to update to version 0.5.4 (build 52)., updateStatus=CRITICAL],pl.baczkowicz.spy.ui.generated.versions.ReleaseStatus@11ea671[fromVersion=0.5.2-46, toVersion=0.5.3-50, updateTitle=Almost there!, updateDetails=Download version 0.5.4 (build 52) and get the edge again!, updateStatus=UPDATE_RECOMMENDED],pl.baczkowicz.spy.ui.generated.versions.ReleaseStatus@3dc0[fromVersion=0.5.4-52, toVersion=0.5.4-52, updateTitle=Living on the edge!, updateDetails=You're on the latest release - [version]., updateStatus=ON_LATEST],pl.baczkowicz.spy.ui.generated.versions.ReleaseStatus@a216fd[fromVersion=0.6.0-beta-26, toVersion=0.6.0-beta-51, updateTitle=Living in the stone age!, updateDetails=There is a new experimental release - 0.6.0 beta (build 52)., updateStatus=UPDATE_RECOMMENDED],pl.baczkowicz.spy.ui.generated.versions.ReleaseStatus@1d592ed[fromVersion=0.6.0-beta-52, toVersion=0.6.0-beta-99, updateTitle=Living on the edge!, updateDetails=You're on an experimental beta release - [version]., updateStatus=ON_LATEST]}], latestReleases=pl.baczkowicz.spy.ui.generated.versions.LatestReleases@16c9d08[latestRelease=<null>]] 

best regards
Werner

**Comment by WernerSch** [comment]
Tool works with Windows 7 fine. Thats ok for me, so i dont need it on the raspberry
so you can close this issue.
sorry

**Comment by kamilfb** [comment]
Cheers
