### ISSUE TITLE
problem with subscriptions

### ISSUE THREAD

**Issue by albangabillon** [eclipse/paho.mqtt-spy#35]
In "manage connections", in the "subscriptions" tab, I cannot add a topic. It is automatically replaced by the /sampleSubscription/ topic. Since I am new to MQTT, I may be missing something.

**Comment by kamilfb** [comment]
You need to look at the note below the topic table. Double click on the row cell to edit, and then press Enter to submit the new value in the row. Let me know if that's any better.

**Comment by albangabillon** [comment]
Thanks for your answer
I did all of this. It is when I try to save the connection settings that the topic reverts back to /sampleSubscription/

**Comment by apollo25466** [comment]
For me in myqtt-spy the connection to AWS IoT is established, it is green, but it is disconnected after about 15 seconds; I have the same problem as albangabillon, changing the topic is not possible; is this the root-cause of my problem of being disconnected from AWS IoT?

**Comment by apollo25466** [comment]
in the log-file I see
2017-10-08 15:22:08,698 INFO  [JavaFX Application Thread     ] [MqttEventHandler              ]  - About to resubscribe to all requested topics
as this topic /sampleSubscription/ is not the right, it disconnects again?

It is also not possible to add another one as a second entry; this second entry is converted afterwards again to /sampleSubscription/;


2017-10-08 15:22:05,693 INFO  [mqtt-spy [ConnectionRunnable for raspi3-SenseHAT-Motion@a2rk7s27z1sdpu.iot.eu-central-1.amazonaws.com:8883]] [MqttAsyncConnectionRunnable   ]  - Connecting client ID [raspi3-SenseHAT-Motion] to server [[ssl://a2rk7s27z1sdpu.iot.eu-central-1.amazonaws.com:8883]]; options = 
============== Connection options ==============
CleanSession                :  true
SocketFactory               :  sun.security.ssl.SSLSocketFactoryImpl@1dc3a86
MqttVersion                 :  0
KeepAliveInterval           :  5
ConTimeout                  :  10
UserName                    :  null
SSLProperties               :  null
WillDestination             :  null
==========================================

2017-10-08 15:22:08,697 INFO  [MQTT Call: raspi3-SenseHAT-Motion] [MqttConnectionResultHandler   ]  - raspi3-SenseHAT-Motion@a2rk7s27z1sdpu.iot.eu-central-1.amazonaws.com:8883 connected
2017-10-08 15:22:08,698 INFO  [JavaFX Application Thread     ] [MqttEventHandler              ]  - About to resubscribe to all requested topics
2017-10-08 15:22:26,966 ERROR [MQTT Rec: raspi3-SenseHAT-Motion] [MqttCallbackHandler           ]  - Connection raspi3-SenseHAT-Motion@a2rk7s27z1sdpu.iot.eu-central-1.amazonaws.com:8883 lost
Verbindung wurde getrennt (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more

**Comment by kamilfb** [comment]
@albangabillon @apollo25466 I'm struggling to reproduce your issue:

I've created a new connection, went to the Subscriptions tab, clicked Add topic button, double clicked on /sampleSubscription/ to edit it, put the new value e.g. test2, press Enter key, click the Apply button. If I also selected 'Create tab' and open this connection, it will subscribe to the correct topic. Are you definitely doing all the above?

On a separate note, you don't need to be predefining your subscriptions, you can connect first, and then add new subscriptions as you need them.

**Comment by albangabillon** [comment]
Hi Kamil, 

As you said I was trying to predefine subscriptions before connection. It is true that if I subscribe while connected then I can apply and save my subscription. 

Sorry for that and thank you for your answer. 

Best Regards 


Alban Gabillon 
Professeur des Universités en Informatique 
Directeur de l’Ecole Doctorale du Pacifique 
Tél.: (+689) 40 80 38 80 (GMT -10:00) 
[ https://sites.google.com/site/albangabillon/home | Home Page ] 
B.P. 6570 - 98702 Faa’a - Tahiti - Polynésie française 


De: "Kamil Baczkowicz" <notifications@github.com> 
À: "eclipse/paho.mqtt-spy" <paho.mqtt-spy@noreply.github.com> 
Cc: "Gabillon" <alban.gabillon@upf.pf>, "Mention" <mention@noreply.github.com> 
Envoyé: Dimanche 12 Novembre 2017 11:48:40 
Objet: Re: [eclipse/paho.mqtt-spy] problem with subscriptions (#35) 



[ https://github.com/albangabillon | @albangabillon ] [ https://github.com/apollo25466 | @apollo25466 ] I'm struggling to reproduce your issue: 

I've created a new connection, went to the Subscriptions tab, clicked Add topic button, double clicked on /sampleSubscription/ to edit it, put the new value e.g. test2, press Enter key, click the Apply button. If I also selected 'Create tab' and open this connection, it will subscribe to the correct topic. Are you definitely doing all the above? 

On a separate note, you don't need to be predefining your subscriptions, you can connect first, and then add new subscriptions as you need them.

**Comment by kamilfb** [comment]
No problem - I'm glad it's fine now.
