### ISSUE TITLE
Mac OS High Sierra with Java SDK 9

### ISSUE THREAD

**Issue by JeffLabonte** [eclipse/paho.mqtt-spy#38]
I am unable to start the program.

This is what I get when I am trying to launch mqtt-spy :

```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:945)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at pl.baczkowicz.mqttspy.configuration.MqttConfigurationManager.<init>(MqttConfigurationManager.java:69)
	at pl.baczkowicz.mqttspy.Main.start(Main.java:63)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 8 more
Exception running application pl.baczkowicz.mqttspy.Main

```

**Comment by JeffLabonte** [comment]
I have tried to clone the program and compile it myself :

mvn compile :

```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eclipse.paho.mqttspy:mqtt-spy-daemon:jar:1.0.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 110, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.eclipse.paho.mqttspy:mqtt-spy:jar:1.0.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 131, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] spy-common
[INFO] spy-common-ui
[INFO] mqtt-spy-common
[INFO] mqtt-spy-daemon
[INFO] mqtt-spy
[INFO] mqtt-spy project
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building spy-common 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-jaxb2-plugin:0.12.0:generate (spy-common) @ spy-common ---
[WARNING] The POM for com.sun.xml.bind:jaxb-impl:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.sun.xml.bind:jaxb-xjc:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] spy-common ......................................... FAILURE [  0.749 s]
[INFO] spy-common-ui ...................................... SKIPPED
[INFO] mqtt-spy-common .................................... SKIPPED
[INFO] mqtt-spy-daemon .................................... SKIPPED
[INFO] mqtt-spy ........................................... SKIPPED
[INFO] mqtt-spy project ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.899 s
[INFO] Finished at: 2017-10-26T19:33:15-04:00
[INFO] Final Memory: 9M/32M
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/local/Cellar/maven/3.5.2/libexec/conf/logging/
constituent[1]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-resolver-provider-3.5.2.jar
constituent[2]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-artifact-3.5.2.jar
constituent[3]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-slf4j-provider-3.5.2.jar
constituent[4]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-resolver-transport-wagon-1.1.0.jar
constituent[5]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/aopalliance-1.0.jar
constituent[6]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/plexus-utils-3.1.0.jar
constituent[7]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/plexus-interpolation-1.24.jar
constituent[8]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/plexus-cipher-1.7.jar
constituent[9]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/guava-20.0.jar
constituent[10]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-repository-metadata-3.5.2.jar
constituent[11]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/slf4j-api-1.7.25.jar
constituent[12]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/jansi-1.16.jar
constituent[13]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-compat-3.5.2.jar
constituent[14]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-plugin-api-3.5.2.jar
constituent[15]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/cdi-api-1.0.jar
constituent[16]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-settings-builder-3.5.2.jar
constituent[17]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-resolver-spi-1.1.0.jar
constituent[18]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/jcl-over-slf4j-1.7.25.jar
constituent[19]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/guice-4.0-no_aop.jar
constituent[20]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/plexus-sec-dispatcher-1.4.jar
constituent[21]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-resolver-util-1.1.0.jar
constituent[22]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/plexus-component-annotations-1.7.1.jar
constituent[23]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/commons-cli-1.4.jar
constituent[24]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-resolver-impl-1.1.0.jar
constituent[25]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/commons-io-2.5.jar
constituent[26]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-builder-support-3.5.2.jar
constituent[27]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-shared-utils-3.1.0.jar
constituent[28]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/wagon-file-2.12.jar
constituent[29]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-core-3.5.2.jar
constituent[30]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/wagon-provider-api-2.12.jar
constituent[31]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/org.eclipse.sisu.inject-0.3.3.jar
constituent[32]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-resolver-connector-basic-1.1.0.jar
constituent[33]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-resolver-api-1.1.0.jar
constituent[34]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-model-builder-3.5.2.jar
constituent[35]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-embedder-3.5.2.jar
constituent[36]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-model-3.5.2.jar
constituent[37]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/wagon-http-2.12-shaded.jar
constituent[38]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/maven-settings-3.5.2.jar
constituent[39]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/org.eclipse.sisu.plexus-0.3.3.jar
constituent[40]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/javax.inject-1.jar
constituent[41]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/jsr250-api-1.0.jar
constituent[42]: file:/usr/local/Cellar/maven/3.5.2/libexec/lib/commons-lang3-3.5.jar
---------------------------------------------------
Exception in thread "main" java.util.ServiceConfigurationError: com.sun.tools.xjc.Plugin: com.sun.tools.xjc.addon.accessors.PluginImpl Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
	at java.base/java.util.ServiceLoader.access$1000(ServiceLoader.java:390)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1227)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1259)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1294)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1379)
	at com.sun.tools.xjc.Options.findServices(Options.java:960)
	at com.sun.tools.xjc.Options.getAllPlugins(Options.java:374)
	at com.sun.tools.xjc.Options.parseArgument(Options.java:688)
	at com.sun.tools.xjc.Options.parseArguments(Options.java:812)
	at org.jvnet.mjiip.v_2.OptionsFactory.createOptions(OptionsFactory.java:136)
	at org.jvnet.mjiip.v_2.OptionsFactory.createOptions(OptionsFactory.java:25)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:311)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlAccessType
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3110)
	at java.base/java.lang.Class.getConstructor0(Class.java:3315)
	at java.base/java.lang.Class.getConstructor(Class.java:2108)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
	... 35 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlAccessType
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 43 more
```

**Comment by kamilfb** [comment]
I will look into that - thanks for reporting

**Comment by tstoeckel** [comment]
+1
same problem, Mac OS 10.12.6

**Comment by kamilfb** [comment]
@JeffLabonte  @tstoeckel as a temporary workaround, could you try adding "--add-modules java.xml.bind"  as a JVM parameter when starting java and see it that works?

**Comment by tstoeckel** [comment]
Thanks, works!

**Comment by rokumar-redknee** [comment]
@tstoeckel 
could you please tell me how did you resolve this, I am having same config like you and same error.

I am actually new to mac, and not able to solve this,.

**Comment by tstoeckel** [comment]
@rokumar-redknee: manually start the jar file from console "java ....", add above option. If it works e.g. put this into a shell script for easy starting.

**Comment by Sermus** [comment]
Adding --add-modules helps, but then it throws exception when i try to create a new connection. Just launching Connections->New Connection causes this:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.fxmisc.richtext.skin.TextFlowExt (file:/Users/1/Downloads/mqtt-spy-1.0.1-beta-b13-jar-with-dependencies.jar) to method javafx.scene.text.TextFlow.getTextLayout()
WARNING: Please consider reporting this to the maintainers of org.fxmisc.richtext.skin.TextFlowExt
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR SpyUncaughtExceptionHandler - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1787)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:465)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784)
	... 41 more
Caused by: java.lang.NoSuchMethodError: org.fxmisc.richtext.skin.TextExt.impl_selectionFillProperty()Ljavafx/beans/property/ObjectProperty;
	at org.fxmisc.richtext.skin.ParagraphText.<init>(ParagraphText.java:108)
	at org.fxmisc.richtext.skin.ParagraphBox.<init>(ParagraphBox.java:74)
	at org.fxmisc.richtext.skin.StyledTextAreaView.createCell(StyledTextAreaVisual.java:396)
	at org.fxmisc.richtext.skin.StyledTextAreaView.lambda$new$117(StyledTextAreaVisual.java:146)
	at org.fxmisc.flowless.CellPool.getCell(CellPool.java:20)
	at org.fxmisc.flowless.CellListManager.cellForItem(CellListManager.java:75)
	at org.reactfx.collection.MappedList.get(MappedList.java:27)
	at org.reactfx.collection.MemoizationListImpl.get(MemoizationList.java:99)
	at org.fxmisc.flowless.CellListManager.getCell(CellListManager.java:64)
	at org.fxmisc.flowless.CellPositioner.getSizedCell(CellPositioner.java:129)
	at org.fxmisc.flowless.CellPositioner.placeStartAt(CellPositioner.java:95)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:181)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:109)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:49)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:66)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1226)
	at org.fxmisc.flowless.VirtualFlowContent.layoutChildren(VirtualFlowContent.java:118)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1226)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1773)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:394)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1098)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1186)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1201)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:276)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Stage.java:475)
	at pl.baczkowicz.spy.ui.BaseViewManager.showEditConnectionsWindow(BaseViewManager.java:319)
	at pl.baczkowicz.spy.eventbus.KBus.notifyConsumer(KBus.java:146)
	at pl.baczkowicz.spy.eventbus.KBus.publish(KBus.java:120)
	at pl.baczkowicz.mqttspy.ui.controllers.MqttSpyMainController.createNewConnection(MqttSpyMainController.java:217)
	... 52 more

**Comment by typemismatch** [comment]
This "java -jar mqtt-spy-1.0.0.jar --add-modules java.xml.bind" on a Mac still fails with the same exception.

**Comment by Sermus** [comment]
In my case adding xml bind cures the original problem but make it fail with another one - something was with skinning in JavaFX judging by the exception.

**Comment by chintan-mishra** [comment]
This problem is also present in clean install of CentOS 7 kernel version 3.10.0-693.17.1.el7.x86_64 and Oracle Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by kamilfb** [comment]
I'm looking into this at the moment.

**Comment by kartben** [comment]
I guess you probably also need javafx.base,javafx.control and probably some other javafx modules in your add-modules clause?

**Comment by kamilfb** [comment]
@kartben nope! no need for add-modules; latest beta works by starting the jar file in the usual way.

**Comment by kamilfb** [comment]
@JeffLabonte @tstoeckel @rokumar-redknee @Sermus @typemismatch @chintan-mishra - could you try the latest beta and see if that resolves the problems you we having? I've tested it on Java 8 (Linux) and Java 9 (Windows 10) - https://github.com/eclipse/paho.mqtt-spy/releases/tag/1.0.1-beta14

**Comment by kartben** [comment]
Oops - I was trying to suggest a fix for @chintan-mishra's and others' issue, but yeah I guess you just fixed it! I'll just go back to my room now :-)

**Comment by kamilfb** [comment]
@kartben This bug was caused by two separate issues. JAXB which was to do with modules, and secondly, RichTextFx doesn't seem to be compatible with Java 9 at all, so not using it at all.

**Comment by viktorovichandrej** [comment]
Trying to build application (ver beta18) in Maven. Got error 
`Exception in thread "main" java.util.ServiceConfigurationError: com.sun.tools.xjc.Plugin: com.sun.tools.xjc.addon.accessors.PluginImpl Unable to get public no-arg constructor
`
I added `--add-modules java.xml.bind` line `jvm.config` and got error:
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found

```
How to solve that problem?
