### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by kamilfb** [eclipse/paho.mqtt-spy#6]
If you need help with configuring or using mqtt-spy, please first review the [Frequently Asked Questions](FAQs) wiki page.

**Comment by acestu** [comment]
Hi, 

Just letting you know your Wiki link above is broken and returns a 404 Not Found

Thanks
Stuart

**Comment by kamilfb** [comment]
@acestu well spotted! fixed now.

**Comment by guillaume-d** [comment]
#46

**Comment by droopy4u** [comment]
general information of my system :

```
tech@LinuMint:SOFT $ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
tech@LinuMint:SOFT $ hostname
LinuMint
tech@LinuMint:SOFT $ uname -a
Linux LinuMint 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
I have the same problem that java is **not** able to find the ‘`main`’ class!

```
tech@LinuMint:SOFT $ java -jar ./mqtt-spy-1.0.1-beta-b18-jar-with-dependencies.jar                                                
Error: Could not find or load main class pl.baczkowicz.mqttspy.Main
```


Despite it is in the jar file : **`pl/baczkowicz/mqttspy/Main.class`**

```
tech@LinuMint:SOFT $ jar -tvf mqtt-spy-1.0.1-beta-b14-jar-with-dependencies.jar | grep mqttspy | grep -i main 
  5016 Tue Mar 13 00:11:38 CET 2018 pl/baczkowicz/mqttspy/Main.class
   917 Tue Mar 13 00:11:36 CET 2018 pl/baczkowicz/mqttspy/ui/controllers/MqttSpyMainController$5.class
  2055 Tue Mar 13 00:11:36 CET 2018 pl/baczkowicz/mqttspy/ui/controllers/MqttSpyMainController$4.class
  1731 Tue Mar 13 00:11:36 CET 2018 pl/baczkowicz/mqttspy/ui/controllers/MqttSpyMainController$3.class
  1728 Tue Mar 13 00:11:36 CET 2018 pl/baczkowicz/mqttspy/ui/controllers/MqttSpyMainController$2.class
 17207 Tue Mar 13 00:11:36 CET 2018 pl/baczkowicz/mqttspy/ui/controllers/MqttSpyMainController.class
  1101 Tue Mar 13 00:11:36 CET 2018 pl/baczkowicz/mqttspy/ui/controllers/MqttSpyMainController$1.class
   455 Tue Mar 13 00:11:38 CET 2018 org/eclipse/paho/mqttspy/Main.class
```

**### Finally I found this problem :**
for more information --> see point 5. - troubleshooting

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

_My troubleshooting ;_

1. So I started to check the java version and to me it looks all ok (out curiosity I also checked with version 11, same problem)

```
tech@LinuMint:SOFT $ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/
tech@LinuMint:SOFT $ ls -als /usr/lib/jvm/                                                                                         
total 36
 4 drwxr-xr-x   5 root root  4096 Jun  8 16:49 .
12 drwxr-xr-x 164 root root 12288 Jun  8 14:00 ..
 0 lrwxrwxrwx   1 root root    25 Apr 19 14:47 default-java -> java-1.11.0-openjdk-amd64
 0 lrwxrwxrwx   1 root root    21 Apr 19 14:47 java-1.11.0-openjdk-amd64 -> java-11-openjdk-amd64
 4 -rw-r--r--   1 root root  2044 Apr 15 23:12 .java-1.11.0-openjdk-amd64.jinfo
 4 drwxr-xr-x   9 root root  4096 Jun  8 16:49 java-11-openjdk-amd64
 0 lrwxrwxrwx   1 root root    20 Apr 15 20:48 java-1.8.0-openjdk-amd64 -> java-8-openjdk-amd64
 4 -rw-r--r--   1 root root  2712 Apr 15 20:48 .java-1.8.0-openjdk-amd64.jinfo
 4 drwxr-xr-x   7 root root  4096 Jun  8 16:36 java-8-openjdk-amd64
 4 drwxr-xr-x   2 root root  4096 Jun  8 16:49 openjdk-11
tech@LinuMint:SOFT $ echo $JAVA_HOME      
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/
tech@LinuMint:SOFT $ java -jar ./mqtt-spy-1.0.1-beta-b18-jar-with-dependencies.jar    
Error: Could not find or load main class pl.baczkowicz.mqttspy.Main
tech@LinuMint:SOFT $ sudo update-alternatives --config java                                                                       
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number:
```

2. So I started to check if openjfx is available (like mentioned in an earlier post)
```
tech@LinuMint:SOFT $ sudo find /usr  -iname "*openjfx*"
[sudo] password for tech:
/usr/share/openjfx
/usr/share/doc/libopenjfx-java
/usr/share/doc/openjfx
/usr/share/doc/libopenjfx-jni
/usr/share/maven-repo/org/openjfx

tech@LinuMint:SOFT $ sudo apt list --installed | grep openjfx
[sudo] password for tech:     

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libopenjfx-java/bionic-updates,bionic-updates,bionic-security,bionic-security,now 11.0.2+1-1~18.04.2 all [installed,automatic]
libopenjfx-jni/bionic-updates,bionic-security,now 11.0.2+1-1~18.04.2 amd64 [installed,automatic]
openjfx/bionic-updates,bionic-security,now 11.0.2+1-1~18.04.2 amd64 [installed]

```


3. [REF : https://github.com/eclipse/paho.mqtt-spy/wiki/FAQs#error-could-not-find-or-load-main-class-plbaczkowiczmqttspymain](https://github.com/eclipse/paho.mqtt-spy/wiki/FAQs#error-could-not-find-or-load-main-class-plbaczkowiczmqttspymain)


```
tech@LinuMint:SOFT $ sudo apt-get install oracle-java8-installer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate
```

4. [REF : https://stackoverflow.com/questions/51010788/unable-to-install-java9-on-ubuntu](https://stackoverflow.com/questions/51010788/unable-to-install-java9-on-ubuntu)

```
tech@LinuMint:SOFT $ sudo apt install default-jre default-jdk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
default-jdk is already the newest version (2:1.11-68ubuntu1~18.04.1).
default-jre is already the newest version (2:1.11-68ubuntu1~18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**How to update the java version 1.8 ???** Because it seems that I just check/update the 1.11 version

5. [REF : https://github.com/kamilfb/mqtt-spy/issues/88](https://github.com/kamilfb/mqtt-spy/issues/88)

Tried also with the classpath `java --cp` returns an error about version 

```
tech@LinuMint:SOFT $ java -cp '/usr/share/openjfx/lib:/usr/share/openjfx/lib/*:mqtt-spy-1.0.1-beta-b18-jar-with-dependencies.jar' pl.baczkowicz.mqttspy.Main
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
